[tool.black]
line-length = 89
exclude = '''
(
    venv\
    __pycache__
)
'''

[tool.flake8]
line_length = 89
extend-exclude = '.git, __pycache__, venv, __init__.py'

[tool.isort]
line_length = 89
lines_after_imports = 2
skip = '__pycache__'

[tool.pre_commit]
exclude = '.git|__pycache__|venv'
